# Copy this file to site-values.yaml and adjust for your environment.
# Only include the keys you need. Helm layers this file on top of values.yaml.

ckan:
  siteTitle: "CKAN"
  siteUrl: "https://<your-host.example.com>"
  sysadminEmail: "admin@example.com"
  sysadminName: "ckan_admin"
  sysadminPassword: "replace-me"

ingress:
  className: replace-me
  hosts:
    - host: <your-host.example.com>
      paths:
        - path: /ckan(/|$)(.*)
          pathType: ImplementationSpecific

pvc:
  storageClassName: replace-me
  size: 5Gi
